{{- if eq (toString .Values.ingress.enabled) "true" }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Name }}
  name: nginx-clusterip-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Name }}
  name: nginx-clusterip-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if ne .Values.ingress.tls.clusterIssuer "" }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.clusterIssuer }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- fromJson . | toYaml | nindent 4 }}
    {{- end }}
spec:
  rules:
  {{- if ne .Values.ingress.hostname "" }}
  - host: {{ .Values.ingress.hostname }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-clusterip-svc
            port:
              number: 80
  {{- if and (eq (toString .Values.ingress.tlsEnabled) "true") (ne .Values.ingress.hostname "") }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ .Release.Name }}-tls-cert
  {{- end }}
{{- end }}
